plugins {
    id 'java-library'
    id 'jacoco'
    id 'com.github.ben-manes.versions' version '0.42.0'
}

allprojects {
    group = 'com.ring-ding-dong'
    version = '0.0.1-SNAPSHOT'

    apply plugin: 'java-library'
    apply plugin: 'jacoco'

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(8)
        }
        sourceCompatibility(JavaVersion.VERSION_1_8)
        targetCompatibility(JavaVersion.VERSION_1_8)
    }

    repositories {
        mavenCentral()
    }

    dependencies {
        testImplementation(libs.junit.jupiter)
        testRuntimeOnly(libs.junit.engine)
    }

    tasks.named('test') {
        useJUnitPlatform()
        finalizedBy jacocoTestReport
    }

    jacocoTestReport {
        dependsOn test
        reports {
            xml.required = true
            html.required = true
        }
    }
}

subprojects {
    tasks.withType(JavaCompile).tap {
        configureEach {
            options.encoding = 'UTF-8'
            options.release = 8
            options.compilerArgs += ['-Xlint:unchecked', '-Xlint:deprecation', '-parameters']
        }
    }
}

project(':core') {
    dependencies {
        api project(':api')
    }
}



['logging', 'metrics', 'tracing'].each { module ->
    project(":impl:$module") {
        dependencies {
            implementation project(':core')
        }
    }
}

project(':examples') {
    dependencies {
        implementation project(':api')
        implementation project(':core')
        implementation project(':impl:logging')
        implementation project(':impl:metrics')
        implementation project(':impl:tracing')
    }
}