name: Jobserv CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'zulu'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run tests
        run: ./gradlew test

      - name: Generate JaCoCo coverage report
        run: ./gradlew jacocoRootReport

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./build/reports/jacoco/jacocoRootReport/jacocoRootReport.xml

      - name: Check test coverage
        run: |
          COVERAGE=$(./gradlew jacocoTestCoverageVerification -PminCoverage=80)
          if [[ $COVERAGE == *"FAILURE"* ]]; then
            echo "Test coverage is below 80%. Failing the build."
            exit 1
          fi

      - name: Generate Javadoc
        run: ./gradlew aggregateJavadoc

      - name: Publish to GitHub Packages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: ./gradlew publish
        env:
          GITHUB_USERNAME: ${{ secrets.GITHUB_USERNAME }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update README with coverage badge
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          COVERAGE=$(grep -oP 'Total.*?([0-9]{1,3})%' build/reports/jacoco/jacocoRootReport/html/index.html | grep -oP '[0-9]{1,3}')
          sed -i "s/coverage-[0-9]*%/coverage-${COVERAGE}%/" README.md
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -m "Update coverage badge" -a || echo "No changes to commit"
          git push

      - name: Deploy Javadoc to GitHub Pages
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/docs/javadoc